#!/usr/bin/env bash

PORT=5901

if ! command -v firewall-cmd >/dev/null 2>&1; then
    echo "firewalld not installed."
    exit 1
fi

sudo systemctl enable --now firewalld

sudo firewall-cmd --permanent --add-port=${PORT}/tcp
sudo firewall-cmd --reload

echo "Current open ports:"
sudo firewall-cmd --list-ports
