# Template reference for Fedora base images.
# The active seed is generated by e2e/scripts/seed.py.
#
# Required behavior:
# - create user wbeam
# - inject SSH key
# - enable sshd
# - configure passwordless sudo
# - install headless or GNOME packages depending on session
# - write /var/lib/wbeam-e2e/base-ready.json
